name: CMake Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release -- -m

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: ShogiAI-windows
          path: build/Release/ShogiAI.exe

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release -- -j 2

      - name: Upload Linux Binary
        uses: actions/upload-artifact@v4
        with:
          name: ShogiAI-linux
          path: build/ShogiAI
